# Generated by Django 3.0.8 on 2020-08-01 17:53

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(default='Комплектующая', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Комплектующая',
                'verbose_name_plural': 'Комплектующие',
            },
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=120, unique=True, verbose_name='Название производителя')),
            ],
            options={
                'verbose_name': 'Производитель видеокарты',
                'verbose_name_plural': 'Производитель видеокарт',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=120, verbose_name='Производитель')),
                ('model', models.CharField(max_length=120, verbose_name='Модель')),
                ('url', models.URLField()),
                ('component_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping_from_ek.Component', verbose_name='Комплектующая')),
            ],
            options={
                'verbose_name': 'Url адресс',
                'verbose_name_plural': 'Url адресса',
            },
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(verbose_name='Картинка')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('model', models.CharField(max_length=120, verbose_name='Модель')),
                ('wed_price', models.CharField(max_length=120, verbose_name='Средняя цена')),
                ('best_price', models.URLField(verbose_name='Лучшая цена')),
                ('component', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping_from_ek.Component', verbose_name='Комплектующая')),
                ('manufacturer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping_from_ek.Manufacturer', verbose_name='Производитель видеокарты')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField(verbose_name='Картинка')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('model', models.CharField(max_length=120, verbose_name='Модель')),
                ('wed_price', models.CharField(max_length=120, verbose_name='Средняя цена')),
                ('best_price', models.URLField(verbose_name='Лучшая цена')),
                ('component', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping_from_ek.Component', verbose_name='Комплектующая')),
                ('manufacturer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping_from_ek.Manufacturer', verbose_name='Производитель процессора')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
    ]
